apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0f7978fa2dc4926a0
    fsType: ext4


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: ebs-static-pv

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: jenkins-deployment

spec:
  replicas: 0

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      app: jenkins

  template:
    metadata:
      labels:
        app: jenkins

    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000  
      nodeSelector:
        disktype: ssd
      containers: 
      - name: jenkins
        image: jenkins/jenkins:lts
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: ebs-vol        
      volumes:
        - name: ebs-vol
          persistentVolumeClaim:
            claimName: ebs-static-pvc
