apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example-pod
spec:
  containers:
  - name: my-nginx
    image: nginx
    volumeMounts:
    - name: storage # Name must match volume name
      mountPath: /data # Container path
  volumes:
  - name: storage # Volume definition
    hostPath:
      path: /data/data # Node/Host path (e.g., /data/data)
      type: DirectoryOrCreate # Type specifies creation if it doesn't exist
