apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    name: jenkins-web
  ports:
  - name: jenkins-port
    port: 8080
    targetPort: 8080
    nodePort: 30020
