apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    name: jenkins-web
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080

  - name: nginx
    image: nginx
    ports:
    - containerPort: 80 
