# Pod Definition referencing the PVC
apiVersion: v1
kind: Pod
metadata:
  name: pvc-example-pod
spec:
  containers:
  - name: my-nginx
    image: nginx
    volumeMounts:
    - name: storage-volume # Name must match volume name below
      mountPath: /usr/share/nginx/html # Container path
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: my-pvc # References the PVC

