apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-07b9511bc6150ec47   # <-- Replace with your EFS ID
  directoryPerms: "700"
reclaimPolicy: Delete
volumeBindingMode: Immediate
