apiVersion: v1
kind: Service
metadata:
  name: tomcat-node-port
spec:
  type: NodePort
  selector:
    name: webapp
  ports:
    - name: tomcat-port
      port: 8080
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
    - name: nginx-port    
      port: 80
      targetPort: 80
      nodePort: 30008
