apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jenkins-vs
  namespace: jenkins
spec:
  hosts:
  - "*"  # Matches the Gateway host
  gateways:
  - jenkins-gateway
  http:
  - route:
    - destination:
        host: jenkins-service # Replace with your ClusterIP service name
        port:
          number: 8080        # The port Jenkins is listening on
