apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: yashusn/react-express-mongo:frontend
        ports:
        - containerPort: 3000
        env:
          #          - name: REACT 
          #            value: "--prefix=/react"
          - name: DANGEROUSLY_DISABLE_HOST_CHECK  # Add this
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000

